{% set data = load_setup_py_data() %}

package:
  name: q2-alignment
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - scikit-bio
    - qiime2 2017.3.*
    - q2-types 2017.3.*
    - mafft

  run:
    - python 3.5*
    - setuptools
    - scikit-bio
    - qiime2 2017.3.*
    - q2-types 2017.3.*
    - mafft

test:
  imports:
    - q2_alignment
    - qiime2.plugins.alignment

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
